### PR TITLE
Update check_omd.py to python3 and added --heal functionality to automatically restart OMD services

### PR DESCRIPTION
**Pull request by lgmu**
Hi,
I updated the script to python3 and added a "--heal" option to automatically restart OMD services if they are stopped.

We use this with a cronjob that executes the script every minute and writes the output to a logfile if a service was restarted.

### CODE REVIEW

**Comment by stdevel** [comment]
Hi @lgmu - that's awesome! Thanks for your support!

One question - which Python version and Linux distributions were you using? I'm testing on CentOS 7 + Python 3.6.8 and have several smaller issues I'm currently fixing.

**Comment by stdevel** [comment]
Hey @lgmu - now the plugin is working for me.

If you could double-check with your installation I'd merge your fix. :)

**Comment by lgmu** [comment]
> Hi @lgmu - that's awesome! Thanks for your support!
> 
> One question - which OMD and Python version and Linux distributions were you using? I'm testing on CentOS 7 + Python 3.6.8 + OMD 4.00 and have several smaller issues I'm currently fixing.

Hi, 

I was testing it with OMD 4.01 and also python 3.6.8 on CentOS 7 and 8. I didn't have any issues. 
I will try your fixed version and let you know if it worked :)

**Comment by lgmu** [comment]
I tested the updated version on centOS 8 with OMD Labs 4.01 and Python 3.6.8 and it also works fine. 
Thank you 👍

**Comment by lgmu** [comment]
Hello, 
are you planning to merge it? :)

**Comment by stdevel** [comment]
Hey @lgmu - sorry didn't get your reply last month!

Thanks a lot for the feedback - I will merge the code now.

Best wishes,
Christian.

**Pull request merged**
